export { default as MarketResearchIcon } from "./marketeq_research.svg";
export { default as MaterialSymbols } from "./material-symbols-light_energy-program-time-used-outline-rounded.svg";
export { default as HealthIcon } from "./healthicons_i-training-class.svg";
export { default as BsxSchoolIcon } from "./bxs_school.svg";
export { default as JournalIcon } from "./mdi_journal-outline.svg";
export { default as Calendaricon } from "./mdi_calendar-outline.svg";
export { default as DashboardIcon } from "./Vector.svg";
export { default as ContentManagementIcon } from "./fluent_content-view-28-regular.svg";
export { default as EventIcon } from "./hugeicons_news-01.svg";
export { default as UserIcon } from "./ph_user.svg";
export { default as SettingsIcon } from "./material-symbols-light_settings-outline.svg";
export { default as LogoutIcon } from "./exit.svg";
export { default as NotificationIcon } from "./Notifcation.svg";
export { default as ArrowDownIcon } from "./Chevron Down.svg";
export { default as EditIcon } from "./tabler_edit.svg";
export { default as RedDeleteIcon } from "./material-symbols_delete-outline.svg";
export { default as AlertIcon } from "./Alert Icon.svg";
export { default as AatfIcon } from "./aatf-icon.svg";
export { default as AfricariceIcon } from "./africarice-icon.svg";
export { default as CabiIcon } from "./cabi-icon.svg";
export { default as CgiarIcon } from "./cgiar-icon.svg";
export { default as CorafIcon } from "./coraf-icon.svg";
export { default as FaraIcon } from "./fara-icon.svg";
export { default as GainIcon } from "./gain-icon.svg";
export { default as GraIcon } from "./gra-icon.svg";
export { default as IcrisatIcon } from "./icrisat-icon.svg";
export { default as IfpriIcon } from "./ifpri-icon.svg";
export { default as IitaIcon } from "./iita-icon.svg";
export { default as IlriIcon } from "./ilri-icon.svg";
export { default as SyngentaIcon } from "./syngenta-icon.svg";
export { default as TheWorldBankIcon } from "./theworldbank-icon.svg";
export { default as WorldfishIcon } from "./worlffish-icon.svg";    
export {default as RoundedCheckIcon} from './roundedcheck-icon.svg'
